Vagrant.configure("2") do |config|
  config.vm.define "buthorS" do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.hostname = "buthorS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    server.vm.provision "shell", path: "src/server.sh"
   end
end
