Vagrant.configure("2") do |config|
  config.vm.define "buthorS" do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.hostname = "buthorS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/server.sh"
   end

  config.vm.define "buthorSW" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.hostname = "buthorSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
